services:
  nginx:
    image: nginx:alpine
    ports:
      - "${APP_PORT:-80}:80"
    volumes:
      - ./backend:/var/www/backend
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - node

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./backend:/var/www/backend
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: ${DB_DATABASE:-devinit}
      DB_USERNAME: ${DB_USERNAME:-user}
      DB_PASSWORD: ${DB_PASSWORD:-password}

  node:
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      WATCHPACK_POLLING: "true"
      NEXT_PUBLIC_API_URL: "http://localhost:8080/api"
    command: npx next dev --webpack -H 0.0.0.0
    tty: true
    stdin_open: true
    # Ensure node_modules is not overwritten by host
    restart: always

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${DB_DATABASE:-devinit}
      POSTGRES_USER: ${DB_USERNAME:-user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT_FORWARD:-5432}:5432"

volumes:
  db-data:
